### PR TITLE
fix scrolling with keyboard shortcuts

### LINKED ISSUE #1528: Keyboard shortcuts, when going up/down, does not scroll the screen.

### PR DESCRIPTION
**Pull request by epicfaace**
fixes #1528

You can now scroll when using up and down arrows. However, using "j" and "k" still does not scroll. Is this intended behavior @percyliang or should it also scroll when using "j" and "k" to navigate?

### CODE REVIEW

**Comment by percyliang** [comment]
Yes, we want j/k to scroll - basically make it mimic the old frontend.

**Comment by yipenghe** [comment]
A minor bug, if the focus is at the first item in worksheet and we press up arrow, the focus changes to the last item in the worksheet

**Comment by epicfaace** [comment]
> A minor bug, if the focus is at the first item in worksheet and we press up arrow, the focus changes to the last item in the worksheet

Will do this as part of #1515.

**Comment by epicfaace** [comment]
This PR has also changed the actual scrolling element to be just the worksheet (as opposed to the body -- note how the scrollbar only starts after the header). This is more in line with the old frontend.

image


old frontend:

image

**Comment by yipenghe** [comment]
> > A minor bug, if the focus is at the first item in worksheet and we press up arrow, the focus changes to the last item in the worksheet
> 
> Will do this as part of #1515.

<s>Thanks for fixing this in #1560 . One other thing, after that fix, currently if we use down to move all the way down, the focus will stop at the last item, but if we use up to move all the way up, it will lose focus for the first one. I remember we added a dummy item to allow adding a new cell, is this behaviour related (so the focus actually went to the dummy item we can't see)? 

I think we should be consistent on both directions (so either don't focus on anything when we press up/down on the first/last item, or let the focus stay on the first/last item)</s>
It actually is the behaviour of the current frontend, good to keep it for now then

**Review by yipenghe — APPROVED** [review]

**Comment by epicfaace** [comment]
> I think we should be consistent on both directions (so either don't focus on anything when we press up/down on the first/last item, or let the focus stay on the first/last item)

Good point. Even though it wasn't in the old version, I think it's a good change -- and I've went ahead and done it.

**Pull request merged**
