### PR TITLE
Refactor fetchInterpretedWorksheet calls into separate "actions.js" file

### PR DESCRIPTION
**Pull request by epicfaace**
This is the first step in maintaining a separation from react components
with the network actions that they call. This will make it easier
to test, maintain, etc.

### CODE REVIEW

**Comment by epicfaace** [comment]
@yipenghe what do you think about this structure for refactoring network calls? If you're good with it I  can do it for all the network calls that exist currently

**Comment by yipenghe** [comment]
> @yipenghe what do you think about this structure for refactoring network calls? If you're good with it I can do it for all the network calls that exist currently

Looks great, more organized, thanks!

**Review by yipenghe — APPROVED** [review]
Let's merge this first so when if we have new network calls we can add to this file

**Comment by percyliang** [comment]
Why use the frontend branch as opposed to master?

**Comment by epicfaace** [comment]
Oops, that was a mistake. Thanks for catching

**Pull request merged**
