### PR TITLE
Upgrade Ubuntu in Docker files

### PR DESCRIPTION
**Pull request by pranavjain**
This PR upgrades the Ubuntu to the 20.04 version. We can upgrade Python once this change is in to avoid any failures.

Please do check this one locally before merging.

### CODE REVIEW

**Comment by pranavjain** [comment]
@epicfaace Can you help debug the failing test cases? They seem to be getting timed out.

**Comment by epicfaace** [comment]
@pranavjain I tried this before and spent quite a while on this and wasn't able to get it to work -- https://github.com/codalab/codalab-worksheets/pull/3753 -- don't think I have bandwidth at the moment to further debug

**Comment by epicfaace** [comment]
For simplicity / ease of merging, I'm splitting this PR up into https://github.com/codalab/codalab-worksheets/pull/4147 and https://github.com/codalab/codalab-worksheets/pull/4146.

**Comment by epicfaace** [comment]
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
process:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
process:     raise exception
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
process:     cursor, statement, parameters, context
process:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
process:     cursor.execute(statement, parameters)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 198, in execute
process:     res = self._query(query)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 304, in _query
process:     db.query(q)
process:   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 217, in query
process:     _mysql.connection.query(self, query)
process: sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')
process: [SQL: 
process: CREATE TABLE bundle_store (
process: 	id BIGINT NOT NULL AUTO_INCREMENT, 
process: 	uuid VARCHAR(63) NOT NULL, 
process: 	owner_id VARCHAR(255), 
process: 	name VARCHAR(255) NOT NULL, 
process: 	storage_type VARCHAR(255), 
process: 	storage_format VARCHAR(255), 
process: 	url VARCHAR(255), 
process: 	authentication VARCHAR(255), 
process: 	authentication_env VARCHAR(255), 
process: 	PRIMARY KEY (id), 
process: 	CONSTRAINT uix_1 UNIQUE (uuid), 
process: 	CONSTRAINT nix_1 UNIQUE (name)
process: )CHARSET=utf8mb4
process:

**Pull request closed without merging**
