### PR TITLE
Make all groups public

### PR DESCRIPTION
**Pull request by maxwang7**
See issue for sanity check tests.
Issue: #671 

Note: marshmallow library was added because I experienced bugs with a higher version number (2.10). Downgrading to 2.6.1 fixed my problems.

### CODE REVIEW

**Comment by percyliang** [comment]
At a high-level looks reasonable to me, but this is the type of thing we really want to double check.  Can @kashizui take a detailed look?

**Comment by kashizui** [comment]
Testing on my own machine now

**Comment by kashizui** [comment]
Almost everything looks good, tried all the test cases you described in #671 and more.
Just one minor thing I noticed:
When I view a bundle that I have `none` permissions on, I can still see all the group permissions defined on that bundle. I think unless I have at least `read` permissions on it, I shouldn't be able to see any group permissions on the bundle (as with any of the other attributes).

```
➜  cl info -v 0xd24cd0
bundle_type               : private
uuid                      : 0xd24cd01b5d954f75bc554dbe2e0acde6
data_hash                 : <none>
state                     : <none>
command                   : <none>
owner                     : <unknown>
name                      : <private>
children:
host_worksheets:
  home-codalab(0x72a6926d82dd4b9d98f05d8c566ebdaf)
permission: none
group_permissions:
  cs224n(0x53976c):all
```

This resulted from our decision to remove one of the conditions in `batch_get_group_permissions()`. I just pushed changes to fix this, by adding a check in `codalab.rest.util.get_bundle_infos()` and in `codalab.rest.worksheets.get_worksheet_info()` that only fetches or includes the group permissions if the user has at least read permission on the object.

**Review by kashizui — APPROVED** [review]
LGTM @maxwang7 have a look at the changes I made and go ahead and merge if you agree with them.

**Pull request merged**
