### PR TITLE
Fix building docker files from scratch

### LINKED ISSUE #3955: Docker server images builds are broken
See https://github.com/codalab/codalab-worksheets/pull/3954

image

How to replicate:
- Check out https://github.com/codalab/codalab-worksheets/pull/3954
- Start codalab (`codalab-service start -bd`)
- Docker images don't build

### PR DESCRIPTION
**Pull request by epicfaace**
The previous ppa doesn't have python3.6 anymore, updated to use a new repository.

### CODE REVIEW

**Comment by jzwang43** [comment]
@epicfaace I tested checking out the branch and building the images. They seem to be working? Anything else I need to do other than `start -bd` to reproduce?

**Comment by epicfaace** [comment]
@jzwang43 it's working because it's currently using the cache as of my latest commit. Try undoing my most recent commit (https://github.com/codalab/codalab-worksheets/pull/3954/commits/52f26a440ef00ee4327ad253bccdd6c18f0c8a70) -- this will cause the cache to bust and then you'll see the error.

**Comment by jzwang43** [comment]
@epicfaace I updated the apt repository and the build should be working now:)

**Review by epicfaace — COMMENTED** [review]
Great! I think we might need to update the other dockerfiles too.

**Comment by jzwang43** [comment]
> Great! I think we might need to update the other dockerfiles too.

Updated! Thanks!

**Comment by jzwang43** [comment]
> Great! I think we might need to update the other dockerfiles too.

Actually we only need the update for 16.04. 20.04 doesn't require any changes.

**Comment by epicfaace** [comment]
lgtm

**Pull request merged**
