### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by epicfaace**

### CODE REVIEW

**Review by percyliang — COMMENTED** [review]
How is the output of all the tests collated?

**Comment by epicfaace** [comment]
They weren't collated. I've just added a change that collates them, though.

**Comment by epicfaace** [comment]
Doesn't seem like the tests are designed so they can work in parallel

**Comment by percyliang** [comment]
What's the limitation?  You'd ideally want to be able to run in parallel.  We would just need different state for each one.

**Pull request closed without merging**
