### PR TITLE
Add keyboard shortcuts for major actions

### PR DESCRIPTION
**Pull request by Levilian**
- insert [i] text after current cell
- upload [u] after current cell
- run [r] after current cell
- [backspace] for deleting
- [enter] for markdown editing
- [ctrl+enter/s] for saving
- [esc] for escaping
- fixed moving to beginning [g g] shortcut
- fixed refreshing worksheet [shift+r] focus

### CODE REVIEW

**Comment by Levilian** [comment]
Fix: #1227, #1514

**Comment by Levilian** [comment]
Item markdown edit[enter] and escape[esc]:
https://recordit.co/3s8dgvsQ3V

**Comment by Levilian** [comment]
Worksheet markdown edit[e], save[ctrl+enter/s], discard[esc]
https://recordit.co/8TUau8nM6A

**Comment by Levilian** [comment]
Add a cell[i], upload[u], and run[r]:
https://recordit.co/4rzlFpTxp5

**Comment by Levilian** [comment]
Deletion [backspace]
https://recordit.co/m3MJbSzh8v

**Comment by Levilian** [comment]
moving to beginning [g g] and refreshing worksheet [shift+r]:
https://recordit.co/RTLPDV6QfN

**Comment by epicfaace** [comment]
- Allow "Delete" key (on windows) to delete
- Allow Command+enter to save current edit on Mac (keep ctrl+enter on windows)

**Comment by epicfaace** [comment]
- Document keyboard shortcut: Add "esc" to go back

**Comment by epicfaace** [comment]
- Bug: when focusing on the terminal and pressing keys, don't register the keyboard shortcuts and select rows on the worksheet
- Add a keyboard shortcut to focus the terminal (not just show/hide)

**Comment by Levilian** [comment]
fixed #1591 as well

**Pull request merged**
