### PR TITLE
Add color to test-cli.py. Fixes #181

### LINKED ISSUE #181: Add color to test-cli.py
Colors for PASS and FAIL messages will help find issues visually.

A more fleshed out summary at the end would also be helpful. (collect all the error messages and reprint them at the end?)

### PR DESCRIPTION
**Pull request by kdexd**
This PR introduces a helper class `Colorizer`, in **test-cli.py**. It consists of methods which format a string by adjusting _ANSI_ escape characters to enable colored output.

Here are some screenshots of output on Circle CI logs:
## image

image

Fixes #181

### CODE REVIEW

**Comment by karandesai-96** [comment]
Hi @percyliang, @kashizui:
I have finished my work in this PR, please let me know if there are any amendments. :white_check_mark:

**Comment by kdexd** [comment]
I introduced a manual error to fail a test, here are the screenshots:

## image

image

**Comment by kdexd** [comment]
Hi @percyliang, @kashizui:
I have finished my work in this PR, please let me know if there are any amendments. :white_check_mark:

**Comment by kashizui** [comment]
Could you squash your first two commits into one (may need push --force)? Otherwise LGTM, @percyliang ?

I appreciate that test failures are searchable by the `[!]` prefix.

**Comment by percyliang** [comment]
Great thanks!
LGTM

**Comment by kdexd** [comment]
I squashed both commits into one ! :white_check_mark: ( 01049c3 )

**Comment by kdexd** [comment]
I  like the idea of this project. I will be eyeing over the documentation and get more comfortable with the source this weekend. I'll ping on any issue if it seems workable to me. Thanks :smiley:

**Pull request merged**
