### PR TITLE
 #44: Use Bower to track frontend dependencies

### PR DESCRIPTION
**Pull request by andreweduffy**
@percyliang 
Now all frontend vendor dependencies are tracked via Bower. This
creates two new directories: static/bower_components for all vendor
dependencies that used to live in static/js/vendor, as well as a
static/custom directory for all custom modified JS/CSS, eg. our
custom Modernizr.

There are a lot of files because I'm [checking in the bower_components](https://addyosmani.com/blog/checking-in-front-end-dependencies/) (considered best practice).

Most important changes:

* Added new `npm` script for building:

    npm run bower # gathers all bower dependencies.

* Removed the `static/vendor` directory, replacing it instead with `static/bower_components` and `static/custom`, the latter being for things like custom.modernizr that we can't pull directly from another source.

* Downside: checking in the bower components take up 233MB in the repository :( I'm not sure if there's a great way around this. There are only two choices to deal with this. a) Don't check in the bower_components or b) check them in and just ignore it. The problem with (b) is that we just made our repo a ton larger, and there's added slowdown when doing a clone/checkout. Problem with (a) is that we won't be able to fetch the bower_components for deployment if GitHub is down (as that is where Bower downloads all components from. At jobs I've run into problems where the external IP of the company had exceeded the Github rate limit, so no one could do a bower install for several hours. Don't want this to happen when trying to deploy...)

### CODE REVIEW

**Comment by percyliang** [comment]
I would say we *definitely* don't want to check in MathJax.  We did that
before, and it was super annoying and we had to purge it out.  (Make sure
you don't just git rm them now and leave them in the history.)

I don't quite appreciate the problem with (a).  The codalab-worksheets repo
is already on github, so if that's down, then we can't update our regular
repo, let alone other stuff.  Also, the build requires other Internet
dependencies like pypi, apt-get, dockerhub, etc., so is this really a big
deal?

Can we put the 'npm run bower' instructions in the wiki (I guess submit it
as a PR for now)?  (I wonder if we should have installation instructions in
the repo, so that it's easier to keep things in sync?)

**Comment by andreweduffy** [comment]
That makes sense, I'll remove MathJax then, should I still keep it in the bower.json so that its fetched when you do npm run bower?

The problem is that Github and the Github API are pretty disparate services, and bower uses the GitHub API. GH doesn't rate limit cloning but it does rate limit API calls for any given IP range. So if many people at Stanford start using bower over a period of several hours, everyone with a Stanford ip could be blocked from using bower for a while. I'm inly bringing it up because I've seen it happen before in production and it's really annoying, you basically need to wait until the window passes and your ip is unblocked to deploy. 
If you feel that the chances of this sort of thing happening are small enough then we can remove bower components from the repo and make that an extra build step. 



On Sun, Jan 31, 2016 at 8:23 AM -0800, "Percy Liang" <notifications@github.com> wrote:










I would say we *definitely* don't want to check in MathJax.  We did that

before, and it was super annoying and we had to purge it out.  (Make sure

you don't just git rm them now and leave them in the history.)



I don't quite appreciate the problem with (a).  The codalab-worksheets repo

is already on github, so if that's down, then we can't update our regular

repo, let alone other stuff.  Also, the build requires other Internet

dependencies like pypi, apt-get, dockerhub, etc., so is this really a big

deal?



Can we put the 'npm run bower' instructions in the wiki (I guess submit it

as a PR for now)?  (I wonder if we should have installation instructions in

the repo, so that it's easier to keep things in sync?)

**Comment by andreweduffy** [comment]
@percyliang Pushed an amended commit that removes MathJax, but still keeps it in the bower.json so it'll be installed when a user runs `npm run bower`. bower_components are now at 60MB, but as I said above they can be removed if you'd prefer to make fetching the components part of deployment

**Comment by percyliang** [comment]
Actually, let's remove all of bower_components out of the repo and rely on
npm run bower to fetch everything (only takes 15 seconds with the exception
of MathJax).

Most of time, we'll have incremental deployments (the virtualenv,
bower_components are already sitting there, so we don't have to pull from
the network), so I think we should be okay.

**Comment by andreweduffy** [comment]
@percyliang Cool, just pushed the change that removes bower components, once this goes in I'll add to the wiki.

**Comment by percyliang** [comment]
Great.  Can you add bower_components to .gitignore and add a brief
description for 'npm run bower' to the README.md in apps/web?

LGTM!

**Pull request merged**
