### PR TITLE
[singularity] implement image runs

### PR DESCRIPTION
**Pull request by adiprerepa**
for https://github.com/codalab/codalab-worksheets/issues/3658

This PR implements the running of singularity images as bundles on codalab. **This change enables singularity bundles to be run by running the bundle in a singularity container.** 

A few abstractions have been created:

`BundleContainer` is a base container interface that contains the actions that every container interface we run is expected to provide.
- `SingularityBundleContainer` is the singularity implementation of `BundleContainer`.
- `DockerBundleContaier` is the docker implementation. It wraps a `docker.Container` and just accesses those methods.

`BundleRunner` is a base executor class that contains just a `run` method that needs to be implement by the docker and singularity counterparts.
- `SingularityBundleRunner` is the singularity implementation.
- `DockerBundleRunner` is the docker implementation.

Currently, no image caching is implemented,  so starting the singularity workers is quite slow (the first steps of a worker are finding out what gpus are available by running nvidia cuda in a container).

### CODE REVIEW

**Comment by adiprerepa** [comment]
todo aditya:
- instead of implementing SIngularityContainer from the docker api container, maybe create a base container class and a docker container and singularity container class that implements those methods. the docker container class would wrap the docker container object (from api).
- put the methods in BundleRunner into the container objects
- `run` method in BundleRunner can be the constructor in the container class
- add good docstrings to base container class

**Comment by epicfaace** [comment]
@adiprerepa can you update the PR description to fully describe what this PR does before I start a review?

**Comment by adiprerepa** [comment]
@epicfaace done

**Comment by epicfaace** [comment]
Closing because we're not focusing on singularity for now

**Pull request closed without merging**
