### PR TITLE
Set up a Bottle server and add some example APIs.

### PR DESCRIPTION
**Pull request by klopyrev**
@kashizui @percyliang

### CODE REVIEW

**Comment by percyliang** [comment]
Overall looks good - thanks!  Just to confirm, the changes to cl.py aren't related to the REST API and don't affect the old functionality, right?

One issue I'd like to bring up is that many users who are not interested in running their own servers install the CLI, so we should allow their install process to be as breezy as possible.  bottle adds more dependencies.  Could we split requirements.txt into requirements-client.txt and requirements-server.txt and modify setup.sh to take an argument [client|server] to install the right dependencies?

**Comment by klopyrev** [comment]
Yes, the changes to cl.py don't affect the old functionality.

I modified the setup script.

**Comment by percyliang** [comment]
LGTM from me, but let's hear what @kashizui says

**Comment by klopyrev** [comment]
@percyliang I made a change to what I think looks cleaner. I'm now saving the bundle model and bundle store in the local thread-local variable. Let me know what you think.

**Comment by percyliang** [comment]
Looks good to me.

On Mon, Feb 1, 2016 at 3:43 PM, Konstantin Lopyrev <notifications@github.com

**Comment by kashizui** [comment]
Looks great! Excited to get cracking on this.
I really like the look of Bottle.

**Pull request merged**
