### PR TITLE
Revival of Stephen's Memory Allocation PR

### PR DESCRIPTION
**Pull request by fabeschan**
Now that we've reverted master, let's see if Stephen's patches pass CLI tests.

Original PR: #800

### CODE REVIEW

**Comment by fabeschan** [comment]
I haven't had much time to look into it but I think the local instance of the rest server crashes so CLI tests fail with that stack trace

**Comment by kashizui** [comment]
Hm. I tested this locally at the time and it was working -- I'll look into this when I get the chance.

**Comment by kashizui** [comment]
Lol it was a silly typo!

**Comment by percyliang** [comment]
Thank goodness we have tests.

**Pull request merged**
