### PR TITLE
Use mousetrap from node modules

### PR DESCRIPTION
**Pull request by epicfaace**
We don't need to use the actual mousetrap files and check them in our code.

### CODE REVIEW

**Comment by epicfaace** [comment]
@Levilian

**Comment by candicegjing** [comment]
@epicfaace Can you squash the commits and rebase to master?

**Comment by epicfaace** [comment]
@candicegjing I've merged master into this branch. You can squash and merge.

**Comment by yipenghe** [comment]
Needs some changes after merging the latest master

**Comment by epicfaace** [comment]
@yipenghe just merged the latest master, it seems to be fine...

**Comment by yipenghe** [comment]
> @yipenghe just merged the latest master, it seems to be fine...

Ah actually it's breaking` inherit-config`. In mousetrap_global_bind.js, me and @Levilian added some functiions for the mousetrap, not sure if they still work properly after your changes. At least for 

> @yipenghe just merged the latest master, it seems to be fine...

I think you didn't pull the latest master? The checks are all failing. In TextEditorItem.js there is another reference for '../../../../util/ws_mousetrap_fork', which makes `codalab_service.py start -bd` failing.

Another thing is I'm not sure if the methods in /frontend/src/util/mousetrap_global_bind.js still work after changing to use the 'mousetrap' package. Me and @Levilian added them.

If you know what might need to be changed, I can also push a commit to adapt the functions I added.

**Comment by epicfaace** [comment]
I don't think this is worth the effort -- I'll just close this for now and we can revisit this later.

**Pull request closed without merging**
