### PR TITLE
Remove last modified date

### LINKED ISSUE #3156: Format date modified to be more human-friendly
Use https://github.com/hustcc/timeago.js

### PR DESCRIPTION
**Pull request by yuqijin**
### Related issues

fixes #3156 

### Screenshots

before:
Screen Shot 2021-01-11 at 9 10 46 PM

after:
Screen Shot 2021-01-11 at 9 11 38 PM

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Comment by percyliang** [comment]
This increases the amount of vertical space dedicated to header info, which is non-ideal.  Is there a way to not do that?  I think it might be more useful for the dashboard.

**Comment by yuqijin** [comment]
> This increases the amount of vertical space dedicated to header info, which is non-ideal.  Is there a way to not do that?  I think it might be more useful for the dashboard.

I see. How about displaying the date in the old format for the worksheets, and display the date in the new format on the dashboard?

**Comment by yuqijin** [comment]
Remove the last_modified_date from regular worksheets to avoid extra vertical space in the header.
Screen Shot 2021-01-12 at 1 09 27 AM

Will add it for the worksheets displayed on the dashboard in a human-friendly format instead.

**Comment by epicfaace** [comment]
Okay, that sounds good. I'll merge this PR for now so that we don't show the last modified date on the header in prod.

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
