### PR TITLE
setup sentry for frontend

### PR DESCRIPTION
**Pull request by adiprerepa**
for https://github.com/codalab/codalab-worksheets/issues/3417

using https://docs.sentry.io/platforms/javascript/guides/react/

### CODE REVIEW

**Comment by adiprerepa** [comment]
okay, that commit had a lot of files changed. Do files get generated when I add a library or something?

**Comment by epicfaace** [comment]
@adiprerepa I think you installed sentry in the wrong place. You have to run `npm install` after running a `cd frontend`. This way, sentry will be installed in `frontend/node_modules`, which is ignored by git.

**Comment by adiprerepa** [comment]
@epicfaace should be ready now

**Comment by jzwang43** [comment]
We still need this https://docs.sentry.io/platforms/javascript/guides/react/usage/ to capture errors? I think we need to do something like `Sentry.captureException(err);`  when errors are cought. This pull request is just adding the module?

**Comment by epicfaace** [comment]
[The docs say,
](https://docs.sentry.io/platforms/javascript/guides/react/)
> Once this is done, all unhandled exceptions are automatically captured by Sentry.

Nevertheless, we probably do want to test this out to ensure the errors are actually being caught.

**Comment by adiprerepa** [comment]
I tested it out, sentry does automatically capture errors. Here is what it looks like when I just added `throw new Error('foo');`:
image
@epicfaace @jzwang43 should we merge this?

**Review by epicfaace — COMMENTED** [review]
We need to make sure that REACT_APP_CODALAB_SENTRY_INGEST_URL and REACT_APP_CODALAB_SENTRY_ENVIRONMENT are actually passed down to the frontend container through docker-compose.yml, though. We may also have to add the variables at build-time as @jzwang43 did in #3463 (https://github.com/codalab/codalab-worksheets/pull/3463/files#diff-d5ad1f3e91f51a1ae9de4052cad0da8231afafb60dd0ef4ce3298c97b101d28eR719). Let's consider this PR blocked until #3463 is merged and we have a better idea of how to pass variables down to the frontend.

**Comment by adiprerepa** [comment]
@epicfaace #3643 merged, can we merge this?

**Comment by epicfaace** [comment]
@adiprerepa Can we add the sentry frontend variable in a way similar to REACT_APP_CODALAB_RECAPTCHA_SITE_KEY  in https://github.com/codalab/codalab-worksheets/pull/3501? Then, once https://github.com/codalab/codalab-worksheets/pull/3501 is merged, we should be good to merge this in as well.

**Comment by adiprerepa** [comment]
@epicfaace should be good to go

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
