### PR TITLE
[WIP] Implement drag and drop

### PR DESCRIPTION
**Pull request by epicfaace**
For #781.

### CODE REVIEW

**Comment by yipenghe** [comment]
A bit busy on the weekend, I will review it on Monday/Tuesday

**Comment by yipenghe** [comment]
Just tested and it seems the functionality isn't finished yet?

**Comment by yipenghe** [comment]
I can't get the dnd working...it's not quite clear when it triggers the dnd feature and it doesn't reorder things

**Comment by epicfaace** [comment]
- Do this for within a bundle table
- Decide whether to do this for worksheet items (either do this for all items, or just remove this functionality)

**Comment by epicfaace** [comment]
Closing as we're putting dnd functionality on hold for now.

**Pull request closed without merging**
