### PR TITLE
Stream file when gzip compressing

### LINKED ISSUE #3011: Large bundles that can't fit in server memory cannot be downloaded by workers
**Describe the bug**

If a worker takes a dependency on a very large bundle (e.g. 3GB) that can't fit in the server's memory, the server is unable to transmit the dependency and thus the worker fails.

The issue is that in https://github.com/codalab/codalab-worksheets/commit/4cc81fc8142efef6b608d6677bec0e85565908b8#diff-2b2d1ef00e8805335562a7967af36158e9140f6c4a5039f3462517795e4d67f6R210-R218, some changes were made to the `gzip_file` function. Now, it does a `data = open_file(file_path).read()`, which attempts to read the entire file into memory---this isn't always going to work.

**To Reproduce**
Steps to reproduce the behavior :
1. Run a bundle on codalab.stanford.edu (host only has 4G memory) that depends on glove.840B.300d (3GB+ file)

**Expected behavior**
The worker downloads the file

**Server Log**
```
2020-11-03 23:19:02,245 Error on request by nfliu(0x9da95d34ca4d4b7a8b271859281d936c):

GET /bundles/0x58947c280ae341b9b270fcc2173dc951/contents/blob/

Query params:


Form params:


JSON body:
<none>

Local variables:
file_path='/juice/u/codalab/var/codalab/home/partitions/default/bundles/0x58947c280ae341b9b270fcc2173dc951'

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 214, in gzip_file
    data = open_file(file_path).read()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 136, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 664, in _fetch_bundle_contents_blob
    fileobj = local.download_manager.stream_file(target, gzipped_stream)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 197, in stream_file
    return file_util.gzip_file(file_path)
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 217, in gzip_file
    raise IOError(e)
OSError

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 214, in gzip_file
    data = open_file(file_path).read()
MemoryError
```

### PR DESCRIPTION
**Pull request by nelson-liu**
Attempting to fix #3011 --- instead of `read()`ing the entire file into memory, make a `GzipFile` and have it write to a `BytesIO` stream.

### CODE REVIEW

**Comment by nelson-liu** [comment]
There's a unit test that does basically this, but here's a sanity check on the repo README:

```
In [1]: import gzip

In [2]: from io import BytesIO

In [3]: from apache_beam.io.filesystem import CompressionTypes
   ...: from apache_beam.io.filesystems import FileSystems

In [4]: def open_file(file_path, mode='r', compression_type=CompressionTypes.UNCOMPRESSED):
   ...:     """
   ...:     Opens the given file. Can be in a directory.
   ...:     """
   ...:     return FileSystems.open(file_path, mode)
   ...:

In [5]: def gzip_file(file_path):
   ...:     """
   ...:     Returns a file-like object containing the gzipped version of the given file.
   ...:     """
   ...:     try:
   ...:         BUFFER_SIZE = 100 * 1024 * 1024  # Zip in chunks of 100MB
   ...:         file_path_obj = open_file(file_path)
   ...:         output = BytesIO()
   ...:         with gzip.GzipFile(fileobj=output, mode='w') as fo:
   ...:             for data in iter(lambda: file_path_obj.read(BUFFER_SIZE), b''):
   ...:                 fo.write(data)
   ...:         output.seek(0)  # Go back to the start of the stream, so read() works
   ...:         return output
   ...:     except Exception as e:
   ...:         raise IOError(e)
   ...:

In [6]: def gzip_file_old(file_path):
   ...:     """
   ...:     Returns a file-like object containing the gzipped version of the given file.
   ...:     """
   ...:     try:
   ...:         data = open_file(file_path).read()
   ...:         return BytesIO(gzip.compress(data))
   ...:     except Exception as e:
   ...:         raise IOError(e)
   ...:

In [7]: gzip.decompress(gzip_file("README.md").read()).decode() == gzip.decompress(gzip_file_old("README.md").read()).decode()
Out[7]: True
```

**Review by teetone — APPROVED** [review]

**Comment by nelson-liu** [comment]
Merging this for now, @yiboliu do you think we can get this in 0.5.27?

**Comment by yiboliu** [comment]
> Merging this for now, @yiboliu do you think we can get this in 0.5.27?

Yes of course. Have been waiting for that.

**Comment by nelson-liu** [comment]
Oops thanks, sorry for the delay!

**Comment by yiboliu** [comment]
> Oops thanks, sorry for the delay!

No worries. You're all good man!

**Comment by epicfaace** [comment]
Oh, thanks for fixing. @nelson-liu do you think this issue was caused by the Apache Beam changes ([which changed this code from using `subprocess`](https://github.com/nelson-liu/codalab-worksheets/commit/4cc81fc8142efef6b608d6677bec0e85565908b8#diff-2b2d1ef00e8805335562a7967af36158e9140f6c4a5039f3462517795e4d67f6L107-L112)), or is it something that always was there?

**Comment by epicfaace** [comment]
Ah, never mind, I see that is the case from your comment on #3011>

**Pull request merged**
