### PR TITLE
Update description for args

### PR DESCRIPTION
**Pull request by epicfaace**
Update descriptions from https://github.com/codalab/codalab-worksheets/pull/4005 to be more accurate

### CODE REVIEW

**Comment by epicfaace** [comment]
Please review when you get a chance @teetone

**Review by wwwjn — APPROVED** [review]

**Comment by wwwjn** [comment]
It seems that this PR needs to rebase

**Comment by epicfaace** [comment]
@wwwjn if you label a PR "ready-to-merge", then once it's approved and CI passes, Mergify will automatically update the branch and then merge it.

**Comment by wwwjn** [comment]
> 

That's cool! I use to manually rebase and I will try "ready-to-merge" label in the future PRs.

**Pull request merged**
