### PR TITLE
Resolve flake8 errors in tests directory and config flake8 property

### PR DESCRIPTION
**Pull request by yiboliu**
### Reasons for making this change
Resolve flake8 errors in tests/ directory, the ultimate goal is to resolve all errors

### Related issues
#2660 

### Checklist

* [ ] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Review by epicfaace — COMMENTED** [review]
Can you also add flake8 on pre-commit.sh?

**Comment by yiboliu** [comment]
> Can you also add flake8 on pre-commit.sh?

My plan is to add it after all errors are resolved

**Comment by yiboliu** [comment]
Something weird: running flake8 locally gets a different result from running in server. Example: ```./tests/unit/rest/worksheets_test.py:9:13: F541 f-string is missing placeholders```
```./tests/unit/rest/base.py:21:13: F541 f-string is missing placeholders```

They didn't show up when running flake8 locally

**Comment by epicfaace** [comment]
@yiboliu did you make sure you're running the same versions of flake8 and python locally as what CI is running?

**Comment by yiboliu** [comment]
> @yiboliu did you make sure you're running the same versions of flake8 and python locally as what CI is running?

Yes. I reinstalled my local flake8 and python is 3.6 right?

**Review by teetone — COMMENTED** [review]
Since we split up the work into smaller PR's, can we close this one now? @yiboliu

**Pull request closed without merging**
