### PR TITLE
Parse uuid from URL

### LINKED ISSUE #89: Parse uuid from URL
I can go ahead and do this, just have to parse worksheet uuid out of URL on client-side instead of filling it in on server-side.

### PR DESCRIPTION
**Pull request by kashizui**
Fixes #89 

just realized we already removed jsxtransformer dependency, but maybe this is useful anyways?

@percyliang @andreweduffy please review

### CODE REVIEW

**Comment by percyliang** [comment]
Should we remove the django worksheet_uuid variable too then?
LGTM

**Comment by kashizui** [comment]
good point

**Comment by kashizui** [comment]
Actually makes the page a lot snappier!

**Comment by percyliang** [comment]
That's good to hear.

**Pull request merged**
