### PR TITLE
Provide better space usage for bundle detail info in a worksheet

### LINKED ISSUE #3566: Better space usage for file browser under bundle detail
File browser of a bundle view in a worksheet should match the size of the screen (including stdout)
When the window narrows or expands, the stdout should always fit the screen

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change

File browser of a bundle view in a worksheet matches the size of the screen

### Related issues

fixes #3566 

### Screenshots
ezgif com-gif-maker (1)

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Comment by percyliang** [comment]
The side panel starts out quite wide.  What happens if you have a stdout with very long lines?

**Comment by yuqijin** [comment]
> The side panel starts out quite wide. What happens if you have a stdout with very long lines?
it looks like this
Screen Shot 2021-06-02 at 10 01 08 PM

**Comment by percyliang** [comment]
What if the stdout were even longer, but the command was short (so the side panel doesn't need that much horizontal space)?

**Comment by yuqijin** [comment]
> What if the stdout were even longer, but the command was short (so the side panel doesn't need that much horizontal space)?
Looks like this: it still occupies lots width since we did not set the max width for it.
ezgif com-gif-maker (2)

**Comment by percyliang** [comment]
Perhaps the side panel could be made narrower, since there's a lot of unused space?

**Comment by yuqijin** [comment]
> Perhaps the side panel could be made narrower, since there's a lot of unused space?

I see. How about this? 
image

**Comment by percyliang** [comment]
Looks great!

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
