### PR TITLE
[do not merge] scheduler benchmarking

### PR DESCRIPTION
**Pull request by adiprerepa**
issue: https://github.com/codalab/codalab-worksheets/issues/3723

### CODE REVIEW

**Comment by adiprerepa** [comment]
todo aditya deploy dev then stress tests

**Comment by adiprerepa** [comment]
image
local run stats

**Comment by epicfaace** [comment]
> stress tests

make a script that launches 10K bundles instead

**Comment by epicfaace** [comment]
Closing this due to inactivity / we're not working on this anymore for now.

**Pull request closed without merging**
