### PR TITLE
Remove source of console errors for jquery-editable-poshytip

### PR DESCRIPTION
**Pull request by andreweduffy**
@percyliang @ChengshuLi 

Please verify console errors are gone now.

### CODE REVIEW

**Comment by percyliang** [comment]
LGTM
Has this error always been there?

**Comment by andreweduffy** [comment]
I don't think so, there may have been a customized poshytip in repo before I went and changed everything with bower. I tried to use my best judgement when making the switch to bower, and saw that no functionality was broken. This is more of a papercut, but it's best not to have any errors in the console

**Comment by kashizui** [comment]
(There was not a customized poshytip. )

**Comment by andreweduffy** [comment]
Guess that answers that :)





On Thu, Feb 11, 2016 at 1:44 AM -0800, "Stephen Koo" <notifications@github.com> wrote:












(There was not a customized poshytip. )

**Pull request merged**
