### PR TITLE
server uses local codalabworker code rather than pypi version in setup

### PR DESCRIPTION
**Pull request by maxwang7**
server uses local codalabworker code rather than pypi version in setup.py; workers will pull that code on check in

### CODE REVIEW

**Review by percyliang — COMMENTED** [review]
I think we should either pip install both codalab and codalabworker into the virtualenv (which I prefer) or neither.

**Comment by fabeschan** [comment]
How would someone use this? Do I go into the repo and run something like `python setup.py server` or `python setup.py dev`?

**Comment by percyliang** [comment]
If you're developing, you git clone and go into the repo and type
`./setup.sh server`.  Why do we have both dev and server?  Can we just
merge them?

At this point, `setup.sh` isn't doing that much, but only there to be a
friendly wrapper around the pypi setup, so it can tell you that virtualenv
is missing, etc.

**Comment by maxwang7** [comment]
The reason I believe this change works (though tests are failing, will need to investigate):
- The server setup code checks out the code from Github (it doesn't do pip install right now)
- Then we pip install codalabworker locally
- When the server is started, it uses `codalab-cli/codalab/bin/cl`.

I could also change the code to do `$env/bin/pip install -e .`, which would install the `codalab` module locally, and then the Docker worker would start the server using `cl` rather than `codalab-cli/codalab/bin/cl`.

Investigating the CircleCI failures now...

**Comment by maxwang7** [comment]
Cool, tests passed, will do a test deployment now.

**Pull request merged**
