### PR TITLE
Remove SQLite support

### PR DESCRIPTION
**Pull request by candicegjing**
This PR is to implement features in #1333

### CODE REVIEW

**Review by percyliang — APPROVED** [review]
LGTM. @epicfaace : did you have anything else in mind?

**Comment by epicfaace** [comment]
Looks good. @candicegjing can you say "fixes #1333" in the PR description next time? That way, it will automatically close the issue once the PR is merged to master.

**Comment by epicfaace** [comment]
I'm not sure if we'd need to change this test too? https://github.com/codalab/codalab-worksheets/blob/e22e2cedaa25a8145c655bdca0720c12468db8e3/tests/model/bundle_model_test.py#L88

**Comment by candicegjing** [comment]
@epicfaace I saw that one as well when I was testing the changes. To change to MySQL, we need a username and password. I am not sure how we want to handle that part in the testing code. Or maybe we can read it from a config file?

**Comment by percyliang** [comment]
Hm, it's probably not worth doing this right now.  I think we can just
remove this test since it's not doing much anyway.

**Comment by candicegjing** [comment]
I double-checked our source code and didn't find anything calling `BundleModelTest`. So I removed the entire class.

**Review by epicfaace — APPROVED** [review]

**Comment by epicfaace** [comment]
> I double-checked our source code and didn't find anything calling `BundleModelTest`. So I removed the entire class.

Yeah, that's expected because it's just a test. Thanks!

**Pull request merged**
