### PR TITLE
1753: fix dev environment. copy over table item logic from master

### PR DESCRIPTION
**Pull request by teetone**
Fixes: #1753 

Copied over table item logic from here: https://github.com/codalab/codalab-worksheets/pull/1680/files

Screen Shot 2019-11-27 at 10 56 15 PM

### CODE REVIEW

**Review by yipenghe — APPROVED** [review]
Remember to run prettier

**Comment by teetone** [comment]
@yipenghe How do I run it?

**Comment by yipenghe** [comment]
> @yipenghe How do I run it?

go into frontend folder `cd frontend` and run 
`prettier --config ./.prettierrc --check 'src/**/*.js' --write`
install prettier first if you don't have it

**Comment by percyliang** [comment]
Can we make this part of the pre-commit.sh script?

**Comment by teetone** [comment]
@percyliang I added the prettify command to the pre-commit script. I will merge this in now, since it's breaking the new frontend.

**Pull request merged**
