### PR TITLE
issue#149: Fix copy/paste to web terminal for Mac OS 

### PR DESCRIPTION
**Pull request by ChengshuLi**
@percyliang 
Currently working well for Firefox and Chrome. Not so well on Safari (need to paste twice). Have tried my best to make it work on Safari but still not ideal. Maybe I can have a look again when I wrap up my other PRs.

### CODE REVIEW

**Comment by percyliang** [comment]
@kashizui can you try this out / review this since you have a mac?

**Comment by kashizui** [comment]
Will do later today!

**Comment by kashizui** [comment]
@ChengshuLi I'm getting this extra <textarea> tag when I do the first paste into the terminal:
screen shot 2016-04-29 at 6 13 32 pm

**Comment by ChengshuLi** [comment]
@kashizui @percyliang 

the bug should be fixed now. My bad..

**Comment by kashizui** [comment]
tested and LGTM

**Comment by kashizui** [comment]
Fixes #33

**Pull request merged**
