### PR TITLE
bump sqlalchemy

### PR DESCRIPTION
**Pull request by epicfaace**
Fixes vulnerabilities (#1096).

### CODE REVIEW

**Review by candicegjing — APPROVED** [review]
LGTM 👍

**Comment by percyliang** [comment]
Is there any subtle changes in behavior to be aware of with the new version?

**Comment by epicfaace** [comment]
Changes - https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#key-changes-core

changes that will probably affect us:
- Coercion of string SQL fragments to text() fully removed (see https://github.com/codalab/codalab-worksheets/blob/8286b1c3439f113ce00840338efbdc5e4feb115f/codalab/model/bundle_model.py#L1428)

changes that we'll need to fix later, perhaps before upgrading to the next sqlalchemy version (1.4):
- “threadlocal” engine strategy deprecated
- convert_unicode parameters deprecated

**Comment by epicfaace** [comment]
Actually, we seem to be fine. The coercion change only affects code such as `.where("somecolumn = 'value'")`, which we don't have.

**Pull request merged**
