### PR TITLE
Add messages to stress test

### PR DESCRIPTION
**Pull request by yiboliu**
### Reasons for making this change
Add messages to stress test to show parts of the test has finished

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Comment by teetone** [comment]
This change is not necessary. You can just check the status page: https://worksheets-dev.codalab.org/worksheets/0x0174eb8eb3ef43cd9394dff419982e46

**Comment by epicfaace** [comment]
It might be useful to show all messages on the stress test output so it's self-contained (because the stress test status page can change once another stress test is run / bundles are manually stopped) -- what do you think @teetone ?

**Comment by teetone** [comment]
> It might be useful to show all messages on the stress test output so it's self-contained (because the stress test status page can change once another stress test is run / bundles are manually stopped) -- what do you think @teetone ?

I rarely check the standard logs just because the output is very large and the status page shows the current test that is running. I only check the output when the script has stopped running and there is an error message. I'm fine with this change too though.

**Review by epicfaace — APPROVED** [review]

**Review by epicfaace — CHANGES_REQUESTED** [review]
Actually, can you make all these messages print out in this function (https://github.com/codalab/codalab-worksheets/blob/425e33d59a738888a500ba3c4da62a8f951b9cef/tests/stress/stress_test.py#L114)?

This will make it easier to keep track of messages, rather than putting the messages directly in the function definitions themselves.

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
