### PR TITLE
Fix file exec permissions changing on upload

### LINKED ISSUE #745: Executable scripts no longer have executable permissions after upload

### PR DESCRIPTION
**Pull request by OrthoDex**
- This PR fixes #745

### CODE REVIEW

**Comment by OrthoDex** [comment]
update: sending the .sh file via a tarred folder works. I'll look into if I can get gzip to work.

**Comment by OrthoDex** [comment]
update: os.stat() for the direct file gives 644, umask seems fine, os.stat() for a file within a directory gives 755 (expected). I am thinking this is something fishy with shutil or similar.

**Comment by OrthoDex** [comment]
update: using `--mode=r+wX` during tarring preserves execution bits. Works on local, but it loses execution bits again when pulling into the running container. There is something between the bundle upload and the bundle extraction inside the container that's removing the execution bits.

**Comment by epicfaace** [comment]
@OrthoDex what's the status with this PR -- are you still working on it?

**Comment by OrthoDex** [comment]
Hey @epicfaace, I have paused working on this PR, the issue is non-trivial right now. Happy to have someone else pick it up!

**Comment by epicfaace** [comment]
Okay, let me close it for now -- if anyone wants to continue, feel free to reopen this PR or create a new one.

**Pull request closed without merging**
