### PR TITLE
Handle public user correctly when getting group permissions info

### LINKED ISSUE #93: Users can see groups on a worksheet they do not belong to.
When viewing public or other worksheets I am able to see groups I do not belong to. 
Related to issue https://github.com/codalab/codalab/issues/959
bba7559a-ef3b-11e4-9958-86f313b99b71

### PR DESCRIPTION
**Pull request by kashizui**
Fixes #93 

Screenshots for all four cases: user in private group, user not logged in, user not in private group, user is root

screen shot 2015-10-11 at 10 35 30 pm
screen shot 2015-10-11 at 10 34 55 pm
screen shot 2015-10-11 at 10 34 57 pm
screen shot 2015-10-11 at 10 35 17 pm

@percyliang @pbhatnagar3 ready for review

### CODE REVIEW

**Comment by percyliang** [comment]
LGTM

(Didn't need screenshots - just use the cl)

**Comment by kashizui** [comment]
Got it—on that note is there a way to "log in" as a public user on the CLI?

**Comment by percyliang** [comment]
Oh, I guess not.  Good point...there should be though - let's add that as
an issue.

**Comment by kashizui** [comment]
On it!

**Pull request merged**
