### PR TITLE
Fix build by pinning markdown dependency

### PR DESCRIPTION
**Pull request by epicfaace**
- Pin markdown dependency
- Update argcomplete to work with the latest version of markdown

### CODE REVIEW

**Comment by epicfaace** [comment]
@pranavjain @teetone @adiprerepa should be ready to review now, build is fixed

**Comment by epicfaace** [comment]
@adiprerepa please review and merge this

**Review by jzwang43 — APPROVED** [review]

**Comment by jzwang43** [comment]
I wasn't requested to review this but I think it's good to merge:)

**Comment by epicfaace** [comment]
Thanks!!!

**Pull request merged**
