### PR TITLE
if no user logged in, doesn't show upload button

### PR DESCRIPTION
**Pull request by maxwang7**
I'm wondering if we should turn off the "New Worksheet" and "New Run" bundles as well. I also wonder if it would make more sense to leave the buttons there but redirect the user to the sign in page when they click on the buttons.

### CODE REVIEW

**Comment by percyliang** [comment]
Actually I think we should do your suggestion of leaving the buttons there
and redirecting the user to sign in.

There's one additional wrinkle: if you're logged in but you don't have
permissions on, then maybe the Upload button should immediately show a
message that you don't have permissions rather than failing?  What's the
right UX for this?

**Comment by fabeschan** [comment]
Agree with leaving the buttons there and redirecting the user to sign in.

Right UX should be fail fast. So make it clear you don't have permissions either by disabling out / greying out the upload button or immediately show a message saying so.

**Comment by maxwang7** [comment]
Sounds good, I agree with Fabian's suggestion of disabling / graying out the buttons if the user is logged in but doesn't have the appropriate permissions to use those buttons.

**Comment by maxwang7** [comment]
Made changes following the suggestions in the conversation. The screenshots below show the new UI:

No user logged in. The buttons show but clicking on any of the three ("Upload"/"New Run"/"New Worksheet") redirects the user:
screen shot 2017-10-22 at 1 22 44 pm

User logged in but doesn't have write permissions. The buttons are grayed out and don't have any additional functionality:

screen shot 2017-10-22 at 1 25 13 pm


User logged in an has edit permission (`all`) on the worksheet

screen shot 2017-10-22 at 1 26 49 pm

**Comment by maxwang7** [comment]
@percyliang @fabeschan

**Comment by percyliang** [comment]
The gray buttons doesn't look like they're disabled - I think the text
should be gray and the border shouldn't be dark...

**Comment by fabeschan** [comment]
I agree with @percyliang . Text should be grey

**Comment by maxwang7** [comment]
Sounds good, also I realized that it doesn't make sense to disable "New Worksheet"...

**Comment by fabeschan** [comment]
Perhaps in the case where no user is logged in, the buttons don't show? Thoughts?

**Comment by percyliang** [comment]
I think it's better to show the buttons grayed out so people know what the potential functionality is.

**Comment by maxwang7** [comment]
I thought we decided earlier that if there is no user logged in that we should show the buttons but redirect the users to the sign in page. I can disable them but I think the redirect policy makes the most sense.

**Comment by percyliang** [comment]
Right, redirect makes sense - let's go with that!

**Comment by maxwang7** [comment]
Great, will merge!

**Pull request merged**
