### PR TITLE
Updated nginx config template

### PR DESCRIPTION
**Pull request by krivard**
...to match the one pasted from max, modulo templating paths.

### CODE REVIEW

**Comment by fabeschan** [comment]
Looks okay to my untrained eyes, but I'll leave it to somebody else more experienced than I am to approve this.

**Comment by percyliang** [comment]
The server setup page describes a way to create nginx files:
https://github.com/codalab/codalab-worksheets/wiki/Server-Setup#start-nginx
Why does this not suffice?

In the future, we will plan to release a dockerized image for running a CodaLab instance very easily, so it's probably not worth doing anything between the Server Setup and the longer term solution.

**Comment by krivard** [comment]
Oh sorry -- this is a fix for #359. The existing template contains the following errors:

- specifies the wrong port for django
- specifies the wrong location for /media
- does not include the REST server
- does not include the bundle service
- does not include /static

The template in this PR is based off of the config file that @maxwang7 pasted in the issue thread, which was the only way I was able to get the server running. Just giving back so that the next person doesn't have to duplicate the debug time :)

The [Server-Setup](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup) instructions for NGINX (on Ubuntu, at least) are incomplete at best, and at worst refer to nonexistant directories & commands. I have an updated version that you're also welcome to pull, but if the docker image server release is imminent then let's go with that instead.

**Comment by fabeschan** [comment]
Merging this as discussed, offline.

**Pull request merged**
