### PR TITLE
Fix display of symbolic links

### PR DESCRIPTION
**Pull request by klopyrev**
Fix the display of symbolic links. It could be useful to see the symbolic link structure in a bundle.

I'm also fixing all the downloading code to disallow following these in case the user tries to download from one.

@percyliang

### CODE REVIEW

**Comment by percyliang** [comment]
Currently, when I checked this code out, I don't see any changes in the interface compared to the old code.  The behavior current behavior is (i) displaying symlinks as regular files (rather than marking something as a symlink) and (ii) allowing users to follow symlinks.  We should make both (i) and (ii) false.

**Comment by klopyrev** [comment]
Sorry, this change also requires a backend change. Try it out with: https://circleci.com/gh/codalab/codalab-cli/371

**Comment by klopyrev** [comment]
Sorry, wrong link.

**Comment by klopyrev** [comment]
Updated with correct one: https://github.com/codalab/codalab-cli/pull/392

That change includes the fix to get_info.

**Comment by percyliang** [comment]
I'm on:
- codalab-worksheets: 36f6bb92c93f20f7244127147ad1a06ef6d48c7c
- codalab-cli: 91ce2ccc03129501f8ea759a16dbdadafb205393
Did npm run build
Uploaded bundle with symlinks.  They still are rendered as regular files and you can follow them arbitrarily.

**Comment by klopyrev** [comment]
Run this code: https://github.com/codalab/codalab-cli/pull/392

**Comment by percyliang** [comment]
I am using that code - when I checkout that branch, I get a git hash of 91ce2ccc03129501f8ea759a16dbdadafb205393.  Is that what you're on?

**Comment by klopyrev** [comment]
I have no idea what you're talking about. Can you send me your archive containing the bundle you're uploading? You could be creating it in the wrong way.

**Comment by klopyrev** [comment]
http://lopyrev-pc:8000/bundles/0x74566a51ef1c46de875f484e046ffdfe/

Same code, same branches.

**Comment by percyliang** [comment]
I can't access lopyrev-pc:8000

**Comment by klopyrev** [comment]
VPN in.

**Comment by klopyrev** [comment]
Ok, try http://klopyrev.net:8000/bundles/0x74566a51ef1c46de875f484e046ffdfe/
in case you don't have VPN set up.


Konstantin

**Comment by percyliang** [comment]
Never mind, I had the right version - it was just when I uploaded the bundle, things had already been expanded.

LGTM

**Pull request merged**
