### PR TITLE
service start

### PR DESCRIPTION
**Pull request by yiboliu**
### Reasons for making this change
Fix the trouble of starting codalab_service once codalab module is pip installed. 

### Related issues
#2510 

### Checklist

* [ ] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Comment by yiboliu** [comment]
This time the codalab_service.py is present:
image

**Review by epicfaace — COMMENTED** [review]
What problem exactly are you fixing with this PR?

**Comment by yiboliu** [comment]
> What problem exactly are you fixing with this PR?

So if you `pip install codalab` in a brand new virtual env, and run `codalab-service start`, you will get errors. This is to solve that error.

**Comment by yiboliu** [comment]
migrated to https://github.com/codalab/codalab-worksheets/pull/2997

**Pull request closed without merging**
