### PR TITLE
Set default value of exit_after_num_runs to maxint in rest API call

### PR DESCRIPTION
**Pull request by candicegjing**
This PR sets the default value of `exit_after_num_runs` to max int in rest call to avoid potential failures.

### CODE REVIEW

**Review by nelson-liu — APPROVED** [review]

**Review by epicfaace — CHANGES_REQUESTED** [review]
I don't think this will work -- see https://github.com/codalab/codalab-worksheets/pull/2403. Let's set it to 999999999 instead?

**Comment by candicegjing** [comment]
> I don't think this will work -- see #2403. Let's set it to 999999999 instead?

I don't think these two are the same issue. #2403 is because the `server_default` needs to take a `string`. Here what I am changing is to ensure when a user uses an older version of the `codalab` package on client side, they can still run their `cl-worker` without a failure of missing column. 
Also just for reference: see comment: https://github.com/codalab/codalab-worksheets/pull/2288#discussion_r429599614 and worker side is defined as follows:
https://github.com/codalab/codalab-worksheets/blob/37d948d6be5068ebb5d60b54ee544fd90b7330d0/codalab/worker/main.py#L144-L149

**Comment by candicegjing** [comment]
@epicfaace If we really think maxint is too large, I think we should make all three places consistent.

**Comment by nelson-liu** [comment]
+1 to making all 3 consistent . 999999999 seems fine to me

**Review by nelson-liu — APPROVED** [review]

**Pull request merged**
