### PR TITLE
changes name of button from 'Discard' to 'Discard Changes'

### PR DESCRIPTION
**Pull request by maxwang7**

### CODE REVIEW

**Comment by kashizui** [comment]
Was this a previously discussed change? I'm not sure that "Revert" is much more intuitive than "Discard"-- maybe "discard changes" is more precise

**Comment by percyliang** [comment]
I thought 'revert' is better than 'discard', which might mean that you're deleting the worksheet.  But how about 'revert changes'?

**Comment by fabeschan** [comment]
Personally I've seen and would prefer "discard changes" more

**Comment by percyliang** [comment]
Works for me

**Pull request merged**
