### PR TITLE
Bugfix for error when removing contents of worksheet

### LINKED ISSUE #270: can't delete contents of worksheet completely
Editing worksheets works fine, except when you try to remove all the contents (in Edit Source).  Then get the Javascript error:

Uncaught TypeError: Cannot read property '0' of null
    at t.<anonymous> (worksheet_interface.js:463)
    at Object.<anonymous> (worksheet_content.js:29)
    at c (jquery.min.js:4)
    at Object.fireWith [as resolveWith] (jquery.min.js:4)
    at k (jquery.min.js:6)
    at XMLHttpRequest.r (jquery.min.js:6)

### PR DESCRIPTION
**Pull request by maxwang7**
An error occurs when a user removes all the content of a worksheet on the web UI and then saves changes. Fixes #270

### CODE REVIEW

**Comment by maxwang7** [comment]
@kashizui Can you take a look when you have time?

**Comment by kashizui** [comment]
What was the erroneous behavior and what is the new behavior after this fix?

**Comment by maxwang7** [comment]
Erroneous behavior:
- Go to any worksheet that you have all permission on.
- Edit the worksheet, remove all contents and save.
- In the JS console you'll see an error.

Reasons for the error: The default focus behavior (in this case) is to focus on the first element -- but that doesn't exist, so the program breaks.

The fix: Default to focus on element -1.

**Comment by maxwang7** [comment]
@kashizui Can you review when you have time?

**Pull request merged**
