### PR TITLE
Kubernetes: make sure dependency mounts have unique names

### PR DESCRIPTION
**Pull request by epicfaace**
Previously, dependency mounts would have a constant name (workdir). This PR ensures that these mounts have unique names instead.

### CODE REVIEW

**Comment by epicfaace** [comment]
@AndrewJGaut @yifanmai can you take a look?

**Comment by AndrewJGaut** [comment]
> @AndrewJGaut @yifanmai can you take a look?

Sorry, was waiting until tests passed to check, but you pointed out that tests have been flaky, so I'll re-run them

**Comment by epicfaace** [comment]
@AndrewJGaut can you take a look?

**Review by AndrewJGaut — APPROVED** [review]

**Comment by epicfaace** [comment]
Test error:

image

**Comment by epicfaace** [comment]
2023-04-26 17:16:13,079 Task exception was never retrieved
future: <Task finished coro=<Worker.start.<locals>.listen() done, defined at /opt/codalab/worker/worker.py:304> exception=FailToCreateError([ApiException()])> /opt/conda/lib/python3.7/asyncio/base_events.py 1591
Traceback (most recent call last):
  File "/opt/codalab/worker/worker.py", line 323, in listen
    await receive_msg()
  File "/opt/codalab/worker/worker.py", line 318, in receive_msg
    self.checkin()
  File "/opt/codalab/worker/worker.py", line 550, in checkin
    self.process_runs()
  File "/opt/codalab/worker/worker.py", line 566, in process_runs
    self.runs[uuid] = self.run_state_manager.transition(prev_state)
  File "/opt/codalab/worker/fsm.py", line 35, in transition
    return self._transition_functions[state.stage](state)
  File "/opt/codalab/worker/worker_run_state.py", line 435, in _transition_from_PREPARING
    shared_memory_size_gb=self.shared_memory_size_gb,
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 151, in start_bundle_container
    raise e
  File "/opt/codalab/worker/runtime/kubernetes_runtime.py", line 148, in start_bundle_container
    pod = utils.create_from_dict(self.k8_client, config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 137, in create_from_dict
    raise FailToCreateError(api_exceptions)
kubernetes.utils.create_from_yaml.FailToCreateError: Error from server (Unprocessable Entity): {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"codalab-run-0x901605362d544b94b6ee06b0cba34922\" is invalid: spec.containers[0].volumeMounts[1].name: Not found: \"tmpcodalabworkerscratchdependencies0x13b6465a282e4860a4ab9ecd98eed142\"","reason":"Invalid","details":{"name":"codalab-run-0x901605362d544b94b6ee06b0cba34922","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"tmpcodalabworkerscratchdependencies0x13b6465a282e4860a4ab9ecd98eed142\"","field":"spec.containers[0].volumeMounts[1].name"}]},"code":422}

**Comment by epicfaace** [comment]
Actually, I think it should be OK to have non-unique names. This may be by design for kubernetes.

**Pull request closed without merging**
