### PR TITLE
Add nicer error message when running workermanager w/o boto3

### PR DESCRIPTION
**Pull request by nelson-liu**
Also removed 2 unused imports, sorry for polluting the diff.

### CODE REVIEW

**Review by percyliang — APPROVED** [review]
Thanks!

**Comment by candicegjing** [comment]
Thanks for making the changes! I am wondering if we would consider adding `boto3` as part a requirement when installing `pip3 install codalab`? Since the worker manager could have more users in the future, manually configuring the required packages might not be ideal. But let me know if I missed anything here.

**Comment by nelson-liu** [comment]
@candicegjing percy had some reasoning in https://github.com/codalab/codalab-worksheets/pull/2330 , and I overall agree . It's a pretty heavyweight dependency for something that I would guess _most_ users who `pip install codalab` won't actually need.

**Comment by candicegjing** [comment]
@nelson-liu I see. That makes sense then!

**Comment by candicegjing** [comment]
@nelson-liu build is failing, can you black the format? Then I'll merge it.

**Comment by nelson-liu** [comment]
oops, done

**Pull request merged**
