### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by kl-chou**
### Reasons for making this change

Adding ancestors cli functionality for CodaLab take-home assignment

### CODE REVIEW

**Comment by epicfaace** [comment]
@kl-chou thanks! Can you add a screenshot of sample output from the `cl ancestors` command? Thanks.

**Comment by kl-chou** [comment]
@epicfaace here are some screenshots of example output from the tests I wrote! 

image
image

**Comment by epicfaace** [comment]
Thanks!

**Comment by kl-chou** [comment]
@epicfaace Ashwin, I realized that my implementation had some issues regarding formatting output. I changed the output formatting and made another commit. Here are some new sample outputs:

image
image
image

**Comment by epicfaace** [comment]
Thanks!

**Pull request closed without merging**
