### PR TITLE
Add items only after bundle copied during wadd

### LINKED ISSUE #504: Improve robustness around invalid bundle references in worksheet items
When `cl wadd` is run and Ctrl-C is pressed, this results in an invalid bundle being created.

### PR DESCRIPTION
**Pull request by kashizui**
Fixes #504 

This prevents items with invalid bundle references from being created.

@percyliang

### CODE REVIEW

**Comment by percyliang** [comment]
@kashizui Copying the items before the bundle was deliberate so that people could see (and edit) the metadata before the contents arrive (just like how we're handling uploading now).  I think we should just have more robust logic to handle invalid bundle references in general, which could arise from other situations too.

**Comment by kashizui** [comment]
@percyliang Got it-- what are your initial thoughts on what this more robust logic would look like, e.g. in the case of a canceled wadd?

**Comment by percyliang** [comment]
In general, any reference to an invalid uuid should just show up gracefully
as <invalid>, which seems to already happen.

 -Percy

**Comment by kashizui** [comment]
I see, so is the issue is void then?

**Comment by percyliang** [comment]
I think it sometimes crashes the page though, especially when we have table
schemas (we're just not very consistent about it).  Need better tests!

**Pull request closed without merging**
