### PR TITLE
Create an indicator for when the cursor is "above" all bundles

### LINKED ISSUE #2406: indicator for when the cursor is "above" all bundles
When you first load a worksheet, when you click out and when you move up beyond the first bundle, the cursor is in an invisible position, which makes it hard to reason about.  Consider adding the blue cursor bar (or a compressed version of it) to an empty space above the first bundle to make the state more intuitive.

### PR DESCRIPTION
**Pull request by michaeldu1**
### Reasons for making this change

Previously unintuitive if there is no current focused item

### Related issues
fixes #2406 

### Screenshots

Screen Shot 2020-08-09 at 5 22 11 PM
Screen Shot 2020-08-09 at 5 22 17 PM

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Comment by percyliang** [comment]
The indicator should be a block that's above all the blocks and is not specific to a table.

**Review by epicfaace — CHANGES_REQUESTED** [review]
- The indicator should appear only once, at the top of the worksheet.
- The indicator should only be visible when no item is focused.

image

**Comment by michaeldu1** [comment]
Screen Shot 2020-08-23 at 10 42 28 PM

**Review by epicfaace — CHANGES_REQUESTED** [review]
It seems that the title of the worksheet moves down a bit when I focus and then unfocus from the dummy header. Can you fix the margins so that this is not the case?

See:

image

image



Also, potentially it would look better if we highlighted this grey space in blue instead (instead of adding space to the top of the white page)?

image

**Comment by epicfaace** [comment]
New screenshot:

image

**Review by epicfaace — APPROVED** [review]

**Pull request merged**
