### PR TITLE
Add a blog for announcements

### PR DESCRIPTION
**Pull request by epicfaace**
The blog now looks like this:

image

### CODE REVIEW

**Comment by yipenghe** [comment]
Would it be better to place it at top maybe?

**Review by candicegjing — APPROVED** [review]
Looks great to me!

**Comment by epicfaace** [comment]
> Would it be better to place it at top maybe?

I don't think so -- we'll probably have many more announcements and we wouldn't want to bloat the top with the list of all anouncements.

**Comment by epicfaace** [comment]
Let's link to mailchimp directly instead.

**Pull request merged**
