### PR TITLE
Change google to msftconnecttest for network request

### PR DESCRIPTION
**Pull request by epicfaace**
Related to https://github.com/codalab/codalab-worksheets/issues/4433 -- let's see if this fixes flakiness.

### CODE REVIEW

**Comment by AndrewJGaut** [comment]
Assuming it passes, we should re-run the test many times through CI to see if it fails again. I'll do that before approving. Thanks for submitting this!

**Comment by yifanmai** [comment]
Suggestion: use a connection test page such as http://www.msftconnecttest.com/connecttest.txt instead ([doc](https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network))

**Comment by epicfaace** [comment]
@AndrewJGaut can you approve? I don't know if this 100% fixes the problem, but at least using a test connection site is an improvement from google.com. Once we merge we can monitor to see if the flakiness for this particular test continues to happen.

**Review by AndrewJGaut — APPROVED** [review]

**Comment by AndrewJGaut** [comment]
> @AndrewJGaut can you approve? I don't know if this 100% fixes the problem, but at least using a test connection site is an improvement from google.com. Once we merge we can monitor to see if the flakiness for this particular test continues to happen.

Agreed. At the very least it's an improvement to use a connection test page anyways.

**Pull request merged**
