### PR TITLE
Change name of general worker docker network

### PR DESCRIPTION
**Pull request by bkgoksel**
Previously the name of the general worker docker network that contains
all the containers was a prefix of the names of the specific internal
and external networks that determine the network connection status.

This caused problems when workers were started on machines with these
networks already existing. The Docker SDK's network search method
returns networks for which the search term is a substring (and in
apparent random order from call to call), so it was
possible for us to pick one of the external or internal networks when
trying to reuse the general network.

In that situation we would try to connect the container to the same
network twice, leading to the annoying endpoint already exists errors.
With this PR, no network name should be a substring of another, so even
when we reuse networks, we should not pick the wrong network.

### CODE REVIEW

**Review by percyliang — APPROVED** [review]
Ah!

**Comment by bkgoksel** [comment]
Looks like the worker went offline after the `resources` test run, which is a bit strange. Could anyone else try to debug this (ie maybe run the resources test locally on this branch and see what's going on)?

**Comment by bkgoksel** [comment]
Ok so somehow this breaks `netcat`. I'm investigating right now.

**Comment by bkgoksel** [comment]
Had to make changes to the `docker-compose` file because the worker container itself was still being added to a Docker network with just the prefix as the name.

Right now the `_general` suffix is hardcoded to match in the compose and worker code files. This is a hacky solution but I don't have bandwidth to investigate a more thorough solution at the moment.

**Review by percyliang — APPROVED** [review]
Nice!

**Pull request merged**
