### PR TITLE
Ensure CPU-only bundles don't have access to GPUs in slurm jobs

### PR DESCRIPTION
**Pull request by nelson-liu**
Right now, if you launch a job that requests only CPUs on a slurm node with GPUs available, it'll parse the GPUSET as "ALL", giving the job access to all of the GPUs. This explicitly sets the GPUSET to `NONE`, a new sentinel value for an empty gpuset (there are some issues with shell quotes and passing down `''` to the slurm worker).

### CODE REVIEW

**Comment by nelson-liu** [comment]
hmm, bug is still there...will keep looking around

**Comment by nelson-liu** [comment]
ok, now it's ready for a look.

**Comment by epicfaace** [comment]
Interesting, how did you notice this issue in the first place?

**Comment by nelson-liu** [comment]
Usually i run cpu-only jobs on nodes that don't have GPUs, but some GPU nodes were recently moved to the queue that was formerly cpu-only. when the bundles were running on those nodes, I was noticing that they were inadvertently using the GPU.

**Review by teetone — APPROVED** [review]

**Pull request merged**
