### PR TITLE
Use props instead of jquery for error message handling

### PR DESCRIPTION
**Pull request by epicfaace**
Also uses a dismissable bootstrap "Alert" for error messages.
Eventually, we should replace the loading sign with a similar
type of change. This is one step in the path of removing
jquery.

This PR builds off #1671, so merge this after that PR is merged.

### CODE REVIEW

**Comment by epicfaace** [comment]
@yipenghe can you review?

**Comment by yipenghe** [comment]
Code looks good, what should I be looking for on the view of frontend?

**Comment by epicfaace** [comment]
> Code looks good, what should I be looking for on the view of frontend?

Hmm, I guess you could test by setting a hard-coded value to be set on this line: https://github.com/codalab/codalab-worksheets/pull/1672/files#diff-f36be677374a909f3276bc2317babfcdR1285

**Review by yipenghe — APPROVED** [review]
Make sure to be careful with the merge conflicts though

**Pull request merged**
