### PR TITLE
issue#43 fixed

### PR DESCRIPTION
**Pull request by ChengshuLi**
@percyliang  
Although it's a one-line change, I actually spend hours figuring out a perfect solution. This one is so far the best, and we could talk in person. 

Thanks for reviewing!

### CODE REVIEW

**Comment by percyliang** [comment]
LGTM - thanks!

**Comment by kashizui** [comment]
@percyliang are we still merging into `develop`?

**Comment by percyliang** [comment]
Yes, always.

**Comment by kashizui** [comment]
@ChengshuLi could you push this change to develop as well? We shouldn't have to worry about resetting `master` though, not a big deal.

**Comment by ChengshuLi** [comment]
Done! Thanks

**Pull request merged**
