### PR TITLE
Fix time displaying issue

### LINKED ISSUE #2380: Bad formatted metadata field time showing NaNyNaNd
Screen Shot 2020-06-09 at 5 05 14 PM

Metadata field **time** shows `NaNyNaNd` again due to changes in PR #2357

### PR DESCRIPTION
**Pull request by candicegjing**
Fixed #2380

This PR is to fix the value displaying at the `time` field
Screen Shot 2020-06-12 at 11 19 19 AM

### CODE REVIEW

**Comment by yipenghe** [comment]
What exactly is s in this case, why do we need a loosely equal to check for the null? Is it actually a undefined rather than null (null == undefined is true, null === undefined is false)? If it's undefined we should check for undefined (=== undefined) instead of using ==

**Comment by candicegjing** [comment]
@yipenghe Ref of the issue that fixed this a while ago: https://github.com/codalab/codalab-worksheets/pull/2037. Both `undefined` and `null` can happen.

**Comment by yipenghe** [comment]
> @yipenghe Ref of the issue that fixed this a while ago: #2037. Both `undefined` and `null` can happen.

I would prefer using two conditions in this case (checking both === undefined and === null) so that we know both conditions can happen

**Comment by yipenghe** [comment]
> @yipenghe Ref of the issue that fixed this a while ago: #2037. Both `undefined` and `null` can happen.

Or we should add a comment here that == is needed to check for both

**Comment by candicegjing** [comment]
> > @yipenghe Ref of the issue that fixed this a while ago: #2037. Both `undefined` and `null` can happen.
> 
> Or we should add a comment here that == is needed to check for both

Yeah, sounds good! This can keep the logic as simple as possible. I am adding a comment here to indicate both situations can happen.

**Review by yipenghe — APPROVED** [review]

**Pull request merged**
